FROM jenkins/jnlp-slave:alpine

ARG JENKINS_URL
ARG JENKINS_SECRET
ARG JENKINS_HOME="/home/jenkins"

ENV JENKINS_HOME=${JENKINS_HOME}

USER root
RUN apk add --update --no-cache wget \
                                curl \
                                ca-certificates \
                                python \
                                py-pip && \
    pip install --upgrade pip awscli

# Install kubectl
RUN wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    mv kubectl /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl && \
    apk del curl wget py-pip

USER jenkins
RUN mkdir ${JENKINS_HOME}/.kube && \
    mkdir ${JENKINS_HOME}/.aws
