apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins-master
spec:
  ports:
    - port: 8080
      name: jenkins-ui
    - port: 50000
      name: jenkins-jnpl
  selector:
    app: jenkins-master
  type: ClusterIP

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      containers:
      - image: mkozinenko/jenkins-master:latest
        imagePullPolicy: "Always"
        name: jenkins-master
        ports:
        - containerPort: 8080
          name: jenkins-ui
        - containerPort: 50000
          name: jenkins-jnpl
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        emptyDir: {}
