apiVersion: v1
kind: Service
metadata:
  name: springboot-demo
  labels:
    app: springboot-demo
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: springboot-demo
    tier: backend
  type: NodePort

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: springboot-demo
  labels:
    app: springboot-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-demo
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: springboot-demo
        tier: backend
    spec:
      containers:
      - image: registry:5000/springboot-demo:latest
        imagePullPolicy: "Always"
        name: springboot-demo
        ports:
        - containerPort: 8080
          name: springboot-demo